# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Release PYPI Package

on:
  release:
    types: [published]

jobs:
  release-build-and-publish-pypi:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/scapi-py
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v5
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          version: "0.9.21"

      - name: Python version
        run: python -V

      - name: Uv version
        run: uv --version

      - name: Install & build the project
        run: |
          uv sync --all-extras
          uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
